/*
 * This file is generated by jOOQ.
 */
package pl.ag.fleet;


import pl.ag.fleet.tables.Company;
import pl.ag.fleet.tables.Driver;
import pl.ag.fleet.tables.Insurance;
import pl.ag.fleet.tables.Overview;
import pl.ag.fleet.tables.ReFuel;
import pl.ag.fleet.tables.Vehicle;
import pl.ag.fleet.tables.VehicleState;


/**
 * Convenience access to all tables in fleet.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /**
   * The table <code>fleet.company</code>.
   */
  public static final Company COMPANY = Company.COMPANY;

  /**
   * The table <code>fleet.driver</code>.
   */
  public static final Driver DRIVER = Driver.DRIVER;

  /**
   * The table <code>fleet.insurance</code>.
   */
  public static final Insurance INSURANCE = Insurance.INSURANCE;

  /**
   * The table <code>fleet.overview</code>.
   */
  public static final Overview OVERVIEW = Overview.OVERVIEW;

  /**
   * The table <code>fleet.re_fuel</code>.
   */
  public static final ReFuel RE_FUEL = ReFuel.RE_FUEL;

  /**
   * The table <code>fleet.vehicle</code>.
   */
  public static final Vehicle VEHICLE = Vehicle.VEHICLE;

  /**
   * The table <code>fleet.vehicle_state</code>.
   */
  public static final VehicleState VEHICLE_STATE = VehicleState.VEHICLE_STATE;
}
