/*
 * This file is generated by jOOQ.
 */
package pl.ag.fleet.tables;


import java.math.BigDecimal;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import pl.ag.fleet.Fleet;
import pl.ag.fleet.Keys;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReFuel extends TableImpl<Record> {

  /**
   * The reference instance of <code>fleet.re_fuel</code>
   */
  public static final ReFuel RE_FUEL = new ReFuel();
  private static final long serialVersionUID = 1L;
  /**
   * The column <code>fleet.re_fuel.id</code>.
   */
  public final TableField<Record, Long> ID = createField(DSL.name("id"),
      SQLDataType.BIGINT.nullable(false).identity(true), this, "");
  /**
   * The column <code>fleet.re_fuel.cost</code>.
   */
  public final TableField<Record, BigDecimal> COST = createField(DSL.name("cost"),
      SQLDataType.NUMERIC(19, 2), this, "");
  /**
   * The column <code>fleet.re_fuel.liters</code>.
   */
  public final TableField<Record, BigDecimal> LITERS = createField(DSL.name("liters"),
      SQLDataType.NUMERIC(19, 2), this, "");
  /**
   * The column <code>fleet.re_fuel.vehicle_id</code>.
   */
  public final TableField<Record, String> VEHICLE_ID = createField(DSL.name("vehicle_id"),
      SQLDataType.VARCHAR(255), this, "");

  private ReFuel(Name alias, Table<Record> aliased) {
    this(alias, aliased, null);
  }

  private ReFuel(Name alias, Table<Record> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  /**
   * Create an aliased <code>fleet.re_fuel</code> table reference
   */
  public ReFuel(String alias) {
    this(DSL.name(alias), RE_FUEL);
  }

  /**
   * Create an aliased <code>fleet.re_fuel</code> table reference
   */
  public ReFuel(Name alias) {
    this(alias, RE_FUEL);
  }

  /**
   * Create a <code>fleet.re_fuel</code> table reference
   */
  public ReFuel() {
    this(DSL.name("re_fuel"), null);
  }

  public <O extends Record> ReFuel(Table<O> child, ForeignKey<O, Record> key) {
    super(child, key, RE_FUEL);
  }

  /**
   * The class holding records for this type
   */
  @Override
  public Class<Record> getRecordType() {
    return Record.class;
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : Fleet.FLEET;
  }

  @Override
  public Identity<Record, Long> getIdentity() {
    return (Identity<Record, Long>) super.getIdentity();
  }

  @Override
  public UniqueKey<Record> getPrimaryKey() {
    return Keys.RE_FUEL_PKEY;
  }

  @Override
  public ReFuel as(String alias) {
    return new ReFuel(DSL.name(alias), this);
  }

  @Override
  public ReFuel as(Name alias) {
    return new ReFuel(alias, this);
  }

  /**
   * Rename this table
   */
  @Override
  public ReFuel rename(String name) {
    return new ReFuel(DSL.name(name), null);
  }

  /**
   * Rename this table
   */
  @Override
  public ReFuel rename(Name name) {
    return new ReFuel(name, null);
  }
}
