CREATE TABLE overview
(
    id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    overview_cost            numeric(19, 2),
    overview_description     character varying(255),
    overview_expiration_date date,
    overview_name            character varying(255),
    vehicle_id               character varying(255)
);

alter table if exists vehicle
    add constraint FKOverview
    foreign key (overview_id)
    references overview