CREATE TABLE vehicle_state
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actual_driver_id bigint,
    liters           numeric(19, 2),
    kilometers       numeric(19, 2),
    time             timestamp without time zone,
    vehicle_id       character varying(255)
);

alter table if exists vehicle
    add constraint FKVehicleState
    foreign key (state_id)
    references vehicle_state