CREATE TABLE insurance
(
    id                        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurance_cost            numeric(19, 2),
    insurance_expiration_date date,
    insurance_name            character varying(255),
    vehicle_id                character varying(255)
);

alter table if exists vehicle
    add constraint FKInsurance
    foreign key (insurance_id)
    references insurance